name: PasteurCraft
version: "1.0"
main: "me.kaeternn.pasteurcraft.PasteurCraft"
api-version: "1.21"
authors: [Grôle]
depend: []
softdepend: []
commands:
    infect:
        aliases: [inf]
        usage: /infect <disease> <player>
        description: Infect the given player with the given disease
        permission: pasteurcraft.infect
        permission-message: You do not have <permission>
    cure:
        aliases: [cr]
        usage: /cure <disease> <player>
        description: Cure the given player with the given disease
        permission: pasteurcraft.cure
        permission-message: You do not have <permission>
    diseaselist:
        aliases: [dl, dlist]
        usage: /diseaselist 
        description: Give all existing diseases
        permission: pasteurcraft.diseaselist
        permission-message: You do not have <permission>
permissions:
    pasteurcraft.*:
        default: op
        children:
            - pasteurcraft.infect
            - pasteurcraft.cure
            - pasteurcraft.diseaselist
    pasteurcraft.infect:
        default: op
    pasteurcraft.cure:
        default: op
    pasteurcraft.diseaselist:
        default: op